# Generated by Django 3.0.4 on 2020-03-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(max_length=200)),
                ('year_founded', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('size_range', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('linkedin_url', models.CharField(max_length=200)),
                ('current_employee_estimate', models.CharField(max_length=200)),
                ('total_employee_estimate', models.CharField(max_length=200)),
            ],
        ),
    ]
