# Generated by Django 3.0.4 on 2020-03-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='country',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='employee',
            name='current_employee_estimate',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='employee',
            name='domain',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='employee',
            name='industry',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='employee',
            name='linkedin_url',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='employee',
            name='locality',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='employee',
            name='size_range',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='employee',
            name='total_employee_estimate',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='employee',
            name='year_founded',
            field=models.CharField(max_length=700),
        ),
    ]
