# Generated by Django 3.0.4 on 2020-04-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_auto_20200316_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='num_2',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
